<?php

namespace App\Helpers;

class VoucherTypeHelper
{
    /**
     * Get voucher type configuration
     */
    public static function getConfig($type)
    {
        $configs = [
            'ISTRV' => [
                'label' => 'Inter Store Transfer',
                'out_label' => 'ISTV NO (Transfer Out)',
                'in_label' => 'ISTRV NO (Receiving)',
                'out_placeholder' => 'Enter ISTV number from sending store',
                'in_placeholder' => 'Enter ISTRV number for receiving',
                'out_required' => false,
                'in_required' => true,
                'icon' => '📥',
                'color' => 'info',
            ],
            'FARV' => [
                'label' => 'Fixed Asset Receiving',
                'out_label' => 'ISFATV NO (Transfer Out)',
                'in_label' => 'ISFATRV NO (Receiving)',
                'out_placeholder' => 'Enter Fixed Asset Transfer Voucher number',
                'in_placeholder' => 'Enter Fixed Asset Receiving Voucher number',
                'out_required' => false,
                'in_required' => true,
                'icon' => '🏗️',
                'color' => 'dark',
            ],
            'UMTRV' => [
                'label' => 'Used Material Transfer Receiving',
                'out_label' => 'UMTR NO (Transfer Out)',
                'in_label' => 'UMTRV NO (Receiving)',
                'out_placeholder' => 'Enter Used Material Transfer number',
                'in_placeholder' => 'Enter Used Material Receiving number',
                'out_required' => false,
                'in_required' => true,
                'icon' => '♻️',
                'color' => 'secondary',
            ],
            'GRV' => [
                'label' => 'Goods Received',
                'out_label' => 'ISTV NO',
                'in_label' => 'Supplier Invoice No',
                'out_placeholder' => 'Enter ISTV number',
                'in_placeholder' => 'Enter supplier invoice number',
                'out_required' => false,
                'in_required' => false,
                'icon' => '📦',
                'color' => 'success',
            ],
            'SIV' => [
                'label' => 'Store Issue',
                'out_label' => 'SIV Pad Ref. No',
                'in_label' => '',
                'out_placeholder' => 'Enter SIV pad reference number',
                'in_placeholder' => '',
                'out_required' => true,
                'in_required' => false,
                'icon' => '📤',
                'color' => 'warning',
            ],
            'TRANSFER_OUT' => [
                'label' => 'Transfer Out',
                'out_label' => 'Out/SIV NO',
                'in_label' => 'Transfer Order No',
                'out_placeholder' => 'Enter out/SIV number',
                'in_placeholder' => 'Enter transfer order number',
                'out_required' => true,
                'in_required' => false,
                'icon' => '📤',
                'color' => 'danger',
            ],
            'SRV' => [
                'label' => 'Store Return Voucher',
                'out_label' => 'Return Voucher No',
                'in_label' => 'Original SIV No',
                'out_placeholder' => 'Enter return voucher number',
                'in_placeholder' => 'Enter original SIV number',
                'out_required' => true,
                'in_required' => false,
                'icon' => '🔄',
                'color' => 'primary',
            ],
            'TTRV' => [
                'label' => 'Temporary Transfer Receiving',
                'out_label' => 'Transfer Out No',
                'in_label' => 'Receiving No',
                'out_placeholder' => 'Enter transfer out number',
                'in_placeholder' => 'Enter receiving number',
                'out_required' => false,
                'in_required' => true,
                'icon' => '📥',
                'color' => 'info',
            ],
            'FIV' => [
                'label' => 'Fuel Issue',
                'out_label' => 'FIV Pad Ref. No',
                'in_label' => 'Vehicle/Equipment No',
                'out_placeholder' => 'Enter fuel issue voucher number',
                'in_placeholder' => 'Enter vehicle or equipment number',
                'out_required' => true,
                'in_required' => false,
                'icon' => '⛽',
                'color' => 'warning',
            ],
            'FRV' => [
                'label' => 'Fuel Receiving',
                'out_label' => 'Supplier Invoice No',
                'in_label' => 'FRV No',
                'out_placeholder' => 'Enter supplier invoice number',
                'in_placeholder' => 'Enter fuel receiving voucher number',
                'out_required' => false,
                'in_required' => true,
                'icon' => '⛽',
                'color' => 'warning',
            ],
            'UMIV' => [
                'label' => 'Used Material Issue',
                'out_label' => 'UMIV Pad Ref. No',
                'in_label' => 'Project/Site',
                'out_placeholder' => 'Enter used material issue voucher number',
                'in_placeholder' => 'Enter project or site name',
                'out_required' => true,
                'in_required' => false,
                'icon' => '♻️',
                'color' => 'secondary',
            ],
            'UMTV' => [
                'label' => 'Used Material Transfer',
                'out_label' => 'UMTV No',
                'in_label' => 'Destination',
                'out_placeholder' => 'Enter used material transfer voucher number',
                'in_placeholder' => 'Enter destination',
                'out_required' => true,
                'in_required' => false,
                'icon' => '♻️',
                'color' => 'secondary',
            ],
            'FGRV' => [
                'label' => 'Finished Good Receiving',
                'out_label' => 'Production Order No',
                'in_label' => 'FGRV No',
                'out_placeholder' => 'Enter production order number',
                'in_placeholder' => 'Enter finished good receiving number',
                'out_required' => false,
                'in_required' => true,
                'icon' => '🏭',
                'color' => 'success',
            ],
            'STORE_RETURN' => [
                'label' => 'Store Return',
                'out_label' => 'Return From',
                'in_label' => 'Return Voucher No',
                'out_placeholder' => 'Enter source location',
                'in_placeholder' => 'Enter return voucher number',
                'out_required' => false,
                'in_required' => false,
                'icon' => '🔄',
                'color' => 'primary',
            ],
            'BEGINNING_BALANCE' => [
                'label' => 'Beginning Balance',
                'out_label' => 'Opening Ref No',
                'in_label' => '',
                'out_placeholder' => 'Enter opening reference number',
                'in_placeholder' => '',
                'out_required' => false,
                'in_required' => false,
                'icon' => '📊',
                'color' => 'secondary',
            ],
        ];
        
        return $configs[$type] ?? [
            'label' => $type,
            'out_label' => 'Reference Number',
            'in_label' => 'Document Number',
            'out_placeholder' => 'Enter reference number',
            'in_placeholder' => 'Enter document number',
            'out_required' => false,
            'in_required' => false,
            'icon' => '📋',
            'color' => 'secondary',
        ];
    }
}
